project:
  type: website

website:
  title: Regression toward the meaning
  site-url: https://blog.horaceg.xyz
  description: "Horace Guy's blog about random things"
  open-graph: true
  navbar:
    background: "#eee"
    title: false
    left:
      - text: Home
        href: /
      - icon: rss
        href: index.xml
    right:
      - text: About
        href: /about.html
      - text: CV
        href: https://resume.horaceg.xyz
        target: _blank
      - icon: github
        href: https://github.com/horaceg
      - icon: twitter
        href: https://twitter.com/h0raceguy
      - icon: linkedin
        href: https://linkedin.com/in/horace-guy
      # - icon: stackoverflow
      #   href: https://stackoverflow.com/9162021

  page-footer:
    center:
      - href: https://blog.horaceg.xyz
        text: blog.horaceg.xyz

  comments:
    giscus: 
      repo: horaceg/blog
  
format:
  html:
    theme: litera
    css: styles.css
    anchor-sections: true
    highlight-style: github

