toc: true
project:
  type: website

website:
  title: "Horace Guy's blog"
  site-url: https://blog.horaceg.xyz
  description: "Horace Guy's blog about random things"
  sidebar:
    contents: auto
  navbar:
    right:
      - text: Posts
        href: /
      - about.qmd
      - text: CV
        href: https://resume.horaceg.xyz
        target: _blank
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/horaceg
      - icon: twitter
        href: https://twitter.com/h0raceguy
      - icon: linkedin
        href: https://linkedin.com/in/horace-guy
      # - icon: stackoverflow
      #   href: https://stackoverflow.com/9162021

  comments:
    giscus: 
      repo: horaceg/blog
  
format:
  html:
    theme: sketchy
    css: styles.css
    anchor-sections: true
    highlight-style: github

